FROM php:8.2-fpm

# Install PHP extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions pdo_mysql mysqli zip

# Install system dependencies
RUN apt-get update && apt-get install -y \
    openssl \
    curl \
    zip \
    unzip \
    git \
    vim \
    nodejs \
    npm \
    iputils-ping \
    systemd

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
